"""add note timestamp

Revision ID: 38974fd6af08
Revises: 
Create Date: 2019-02-26 16:29:10.715274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38974fd6af08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'timestamp')
    # ### end Alembic commands ###
